apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: fib-client
      image: pgaida/fib-client
      ports:
        - containerPort: 3000