FROM node:alpine

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]

# There is an issue with permissions in regards to Linux hosts (which includes Windows WSL2)
# So the code must be placed in home of the node user and the package.json must be owned by node.
# Also there is an issue by detecting the code changes within the react app. It is a known issue and the workaround
# says you must the the env variable CHOKIDAR_USEPOLLING to true.
# Run command with volumes to edit code directly:
# sudo docker run -it -p 3000:3000 -e CHOKIDAR_USEPOLLING=true -v /usr/src/app/node_modules -v ${pwd}:/usr/src/app IMAGE_NAME
# the first volume arg says that we dont want to map this specific folder to the host so it dont get "overriden"
