FROM node:alpine

WORKDIR '/usr/src/app'

COPY package.json .
RUN npm install
COPY . .

CMD ["npm", "run", "start"]

# Run command with volumes to edit code directly:
# sudo docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v ${pwd}:/usr/src/app IMAGE_NAME
# the first volume arg says that we dont want to map this specific folder to the host so it dont get "overriden"